// <auto-generated />
namespace InventoryMangager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class renamedEquipmentToItemAndDeletedUnusedTestClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamedEquipmentToItemAndDeletedUnusedTestClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201808210026473_renamedEquipmentToItemAndDeletedUnusedTestClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
