// <auto-generated />
namespace InventoryMangager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedForeidnKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedForeidnKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201808202024514_addedForeidnKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
